name: Lighthouse CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build
        env:
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: lighthouse-test-secret
          GOOGLE_CLIENT_ID: dummy-client-id
          GOOGLE_CLIENT_SECRET: dummy-client-secret

      - name: Start Next.js server
        run: npm start &
        env:
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: lighthouse-test-secret
          GOOGLE_CLIENT_ID: dummy-client-id
          GOOGLE_CLIENT_SECRET: dummy-client-secret

      - name: Wait for server
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            http://localhost:3000
          uploadArtifacts: true
          temporaryPublicStorage: true
